// Generated by Selenium IDE
package edu.pitt.cs;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HIGHLIGHTEXPENSETESTTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hIGHLIGHTEXPENSETEST() {
    // Test name: HIGHLIGHT_EXPENSE_TEST
    // Step # | name | target | value
    // 1 | open | http://127.0.0.1:5000/ | 
    driver.get("http://127.0.0.1:5000/");
    // 2 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 3 | type | id=username | Bob
    driver.findElement(By.id("username")).sendKeys("Bob");
    // 4 | type | id=password | 1234
    driver.findElement(By.id("password")).sendKeys("1234");
    // 5 | click | css=input:nth-child(4) | 
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    
    assertEquals(driver.findElement(By.xpath("//td[2]")).getText(), "2023-05-22");
    // 7 | assertText | xpath=//td | Groceries
    assertEquals(driver.findElement(By.xpath("//td")).getText(), "Groceries");
    // 8 | assertText | xpath=//td[3] | $500
    assertEquals(driver.findElement(By.xpath("//td[3]")).getText(), "$500");
  }
}
